### ISSUE TITLE
Invalid Array Index Error

### ISSUE THREAD

**Issue by patrickmay** [lmj/lparallel#23]
I added this to my code:

    (ql:quickload :lparallel)
    (setf lparallel:*kernel* (lparallel:make-kernel 32))

then changed one call from reduce to preduce.  When I ran the previously working code I got this error:

    debugger invoked on a SB-INT:INVALID-ARRAY-INDEX-ERROR in thread
    #<THREAD "lparallel" RUNNING {1005E5F6E3}>:
      Invalid index 64 for (SIMPLE-ARRAY (UNSIGNED-BYTE 64)
                            (64)), should be a non-negative integer below 64.

This is on a Debian box with 8 quad-core CPUs and SBCL 1.3.3.

Any idea what could be causing this?

**Comment by lmj** [comment]
How do I reproduce the error? The following works for me.

    (defun test ()
      (let* ((n 64)
             (a (make-array n :element-type '(unsigned-byte 64))))
        (map-into a (let ((x 0))
                      (lambda () (incf x))))
        (assert (= (/ (* n (1+ n)) 2)
                   (lparallel:preduce #'+ a)))))

**Comment by nneuss** [comment]
I was hit by a similar error some time ago.  IIRC the reason was that I accessed some hash-tables concurrently.  For ordinary hash-tables this seems to be only allowed (hopefully!  I do not know if there is any guarantee) if the hash-table structure is static, i.e. no new entries are created.

**Comment by patrickmay** [comment]
That looks like the issue, nneuss.  I had memoization using a hash table enabled.  When I turned that off, the call to preduce worked fine.  Interestingly, Clozure CL on OS X worked fine with the memoization enabled.

Thanks for the help and thanks to lmj for making lparallel available.

**Comment by luismbo** [comment]
@patrickmay CCL's hash-tables are thread-safe by default.

**Comment by patrickmay** [comment]
Good to know, @luismbo, thanks.
