### ISSUE TITLE
Please provide an equivalent to LOCK-HELD-P

### ISSUE THREAD

**Issue by phmarek** [lmj/lparallel#27]
so that there's a portable way to put sanity checks in the code.

Thanks a lot!

**Comment by phmarek** [comment]
I believe the SBCL convention is `HOLDING-LOCK-P`, which might be better.

**Comment by lmj** [comment]
lparallel doesn't expose low-level locks at all. The only thing close would be `with-locked-queue`, which doesn't give out the lock but implicitly demands that the `*/no-lock` functions be used inside it.

It would seem that the place to add `lock-held-p` or `holding-lock-p` would be bordeaux-threads. That's the level of abstraction for locks, whereas lparallel sits on top of that.

**Comment by phmarek** [comment]
Okay, thanks; seems I got confused about `lparallel.thread-util:make-lock` and similar things.

Will ask on B-T.

Thanks a lot!
